Feature/sample create
jomaskill/lageevo-covid19 pull request #4
Opened 2020-07-07 17:06 UTC by Heffx

2020-07-07 18:50 UTC, jomaskill commented on app/Http/Controllers/SampleController.php
> +            'email' => 'required',
regra email

2020-07-07 18:51 UTC, jomaskill commented on app/Http/Controllers/SampleController.php
> +            'gal_requisition' => 'nullabel',
nullable

2020-07-07 18:52 UTC, jomaskill commented on app/Http/Controllers/SampleController.php
> +            'age' => 'required|numeric|min:0|max:150',
use 'between'

2020-07-07 18:53 UTC, jomaskill commented on app/Http/Controllers/SampleController.php
> +            'sex' => 'required',
faça o mesmo dos campos enum

2020-07-07 18:54 UTC, jomaskill commented on app/Http/Controllers/SampleController.php
> +            'collect_method' => 'required|in:'.$collect_method = implode(",",sample::COLLECT_METHOD),
não é necessária iniciar uma variável e atribuir valor para ela
ex:
`'required|in:'.implode(",", sample::PATIENT_STATUS)`

2020-07-07 18:55 UTC, jomaskill commented on app/Http/Controllers/SampleController.php
> +
Corrigir o mesmo da validação de create

2020-07-07 18:56 UTC, jomaskill commented on app/sample.php
> +        'id',
chave primaria não é fillable

2020-07-07 18:56 UTC, jomaskill commented on app/Http/Controllers/SampleController.php
> +        ];
faltando 'user_id'

2020-07-07 18:57 UTC, jomaskill commented on database/migrations/2020_07_04_151552_create_samples_table.php
> +            $table->softDeletes();
falta o campo user_id e a definição de chave estrangeira

2020-07-07 18:57 UTC, jomaskill commented on routes/web.php
> +Route::resource('sample','SampleController');
colocar no plural

2020-07-07 18:59 UTC, jomaskill commented on app/sample.php
> +}
Falta a relação com a tabela User n:1

https://laravel.com/docs/7.x/eloquent-relationships#one-to-many

2020-07-07 19:58 UTC, viniciusgrilo commented on app/Http/Controllers/SampleController.php
> +        ];
sample nao tem relação com user

2020-07-07 20:59 UTC, jomaskill commented on app/Http/Controllers/SampleController.php
> +        ];
como assim?

2020-07-07 22:42 UTC, viniciusgrilo commented on app/Http/Controllers/SampleController.php
> +        ];
deixa pra la kkkk

2020-07-08 19:44 UTC, jomaskill requested changes
efetuar mudanças

2020-07-10 00:15 UTC, jomaskill commented on app/Http/Controllers/SampleController.php
> +        return $this->model()::with('users')->get();
concerta

2020-07-10 00:15 UTC, jomaskill commented on app/Http/Controllers/SampleController.php
> +        return $this->model()::with('users')->get();
volta ao que era

2020-07-10 00:16 UTC, jomaskill commented on app/Http/Controllers/SampleController.php
> +            'sex' => 'required|in:'.$sex = implode(",",sample::SEX),
tira $sex =

2020-07-10 00:16 UTC, jomaskill commented on app/Http/Controllers/SampleController.php
> +            'sex' => 'sometimes|in:'.$sex = implode(",",sample::SEX),
msm de cima

2020-07-10 00:16 UTC, jomaskill commented on app/Http/Controllers/SampleController.php
> +            'user_id' => 'sometimes|exists:users,id',
int

2020-07-10 00:16 UTC, jomaskill commented on app/Http/Controllers/UserController.php
> +        return $this->model()::with('samples')->get();
retorna ao que era

2020-07-10 00:17 UTC, jomaskill commented on app/sample.php
> +        return $this->belongsTo(User::class,'user_id');
pode remover 'user_id'

2020-07-10 00:18 UTC, jomaskill commented on database/factories/SampleFactory.php
> +        'user_id' => 1,
vc pode utilizar um factory(user)->id

2020-07-10 18:12 UTC, jomaskill commented on app/Http/Controllers/SampleController.php
> +            'sex' => 'required|in:'.$sex = implode(",",Sample::SEX),
tira $sex

2020-07-10 18:12 UTC, jomaskill commented on app/Http/Controllers/SampleController.php
> +            'beginning_symptom_date' => 'required|in:'.$beginning_symptom_date = implode(",",Sample::BEGINNING_SYMPTOM_DATE),
tira $beginning_symptom_date

2020-07-10 18:12 UTC, jomaskill commented on app/Http/Controllers/SampleController.php
> +            'collect_method' => 'required|in:'.$collect_method = implode(",",Sample::COLLECT_METHOD),
remove a variavel

2020-07-10 18:13 UTC, jomaskill commented on app/Http/Controllers/SampleController.php
> +        return array(
deixa com `[ ]`

2020-07-10 18:22 UTC, jomaskill commented on database/factories/SampleFactory.php
> +        'user_id' => User::all()->random()->id,
quando colocar um user_id, ele tem que existir no banco de dados, então nessa linha tem que ser criada um user usando a factory, e usar o Id gerado.
ex $factory(\App\User::class)->create()->id

2020-07-10 18:23 UTC, jomaskill commented on database/factories/SampleFactory.php
> +$factory->define(Sample::class, function (Faker $faker) {
importe a $factory nessa função, para poder utilizar em "user_id"

2020-07-10 23:38 UTC, jomaskill approved these changes

2020-07-10 23:39 UTC, closed without merging